version: "3.9"

services:

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - iotnet

  node-red:
    build:
      context: ./node-red
      dockerfile: Dockerfile
    container_name: node-red
    restart: unless-stopped
    ports:
      - "1880:1880"
    environment:
      - NODE_RED_ENABLE_PROJECTS=true
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./node-red/data:/data
    depends_on:
      - mosquitto
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - iotnet

  python-app:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: python-app
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - TZ=America/Argentina/Cordoba
      - RTSP_USER=${RTSP_USER}
      - RTSP_PASS=${RTSP_PASS}
      - RTSP_IP=${RTSP_IP}
      - RTSP_PORT=${RTSP_PORT}
      - RTSP_PATH=${RTSP_PATH}
      - MQTT_HOST=${MQTT_HOST}
      - MQTT_PORT=${MQTT_PORT}
    volumes:
      - ./python/src:/app/src
      - ./python/config.yaml:/app/config.yaml
    depends_on:
      - mosquitto
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - iotnet

networks:
  iotnet:
    driver: bridge